### ISSUE TITLE
high level feedback:

### ISSUE THREAD

**Issue by stefanpenner** [embersherpa/ember-ajax#1]
i like the concept, nice to transition to something more focused, but not yet ember-fetch (as some have concerns).

- [x] lets remove directories not used (like app) – maybe we want to make a task in ember-cli to cleanup unused for people.
- [x] https://github.com/embersherpa/ember-ajax/blob/master/addon/index.js can be `export { default } from './request';`
- [x] lets name this anoymous function so profiles/debuggers/callstacks include a useful name: https://github.com/embersherpa/ember-ajax/blob/master/addon/make-promise.js#L17
- [x] https://github.com/embersherpa/ember-ajax/blob/master/addon/make-promise.js#L27 ^^
- [x] i believe new ember, doesn't need this run: https://github.com/embersherpa/ember-ajax/blob/master/addon/make-promise.js#L18 worth exploring and reporting back.
- [x] ED always rejects errors here: https://github.com/embersherpa/ember-ajax/blob/master/addon/make-promise.js#L28 maybe we should explore that?

**Comment by taras** [comment]
>  i believe new ember, doesn't need this run
I tested this by evaluating a computed property in the callback and I didn't get a warning, so it seems like this is no longer necessary.

> ED always rejects errors here
`ic-ajax` has a different error response signature. doing anything in that handler would be limiting and break (what's likely) the least tested portion of user's apps. I'm not going to touch the `ic-ajax` callback handler. It should be deprecated in favour of the AjaxService that I implemented.
